Feature/login
DragonTamer117/Vue_Webshop pull request #2
Opened 2023-05-21 16:23 UTC by foekinator656

2023-05-21 16:39 UTC, DragonTamer117 commented
Please wait till tomorrow for me to review this, I have to update my project.
Right now I can't review, since I'm having some internet issues and I am answering this through my phone.

2023-05-22 08:36 UTC, DragonTamer117 requested changes

2023-05-22 08:36 UTC, DragonTamer117 commented on src/components/admin/login/register/register.vue
> +            role: 0,
Role is a string that the backend pushes out from.
Please change this to:
`role: ""`

2023-05-22 08:36 UTC, DragonTamer117 commented on src/components/shared/ApiService.ts
This file seems redundant, please remove it.

2023-05-22 08:36 UTC, DragonTamer117 commented on src/components/shared/order/order-item/order-item.vue
> +<!--  <a-->
The HTML here is commented, please remove this.

2023-05-22 08:36 UTC, DragonTamer117 commented on src/components/shared/order/order.vue
Remove commented code here as well.

2023-05-22 08:36 UTC, DragonTamer117 commented on src/components/shared/order/payment/payment.vue
Remove comments.

2023-05-22 08:36 UTC, DragonTamer117 commented on src/router.js
Remove comments.

2023-05-22 11:31 UTC, foekinator656 commented on src/router.js
i am keeping the comments for later

2023-05-22 11:32 UTC, foekinator656 commented
@DragonTamer117 please check again please

2023-05-24 16:57 UTC, DragonTamer117 commented on src/router.js
That's okay

2023-05-24 16:58 UTC, DragonTamer117 reviewed
LGTM!

2023-05-24 17:00 UTC, DragonTamer117 approved these changes
LGTM now, wrong branch. So some changes were not needed, next time watch the pull request to what branch.

2023-05-24 19:17 UTC, merged