Feature/create cart
DragonTamer117/Vue_Webshop pull request #3
Opened 2023-06-04 19:13 UTC by foekinator656

a working cart!

2023-06-04 19:14 UTC, foekinator656 commented
@DragonTamer117

2023-06-05 11:06 UTC, DragonTamer117 requested changes

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/admin/login/login.vue
> +import {StoreVars} from "@/components/shop/shop-item/StoreVars";
Needs spaces in between. So like:
`import { StoreVars } from "@/components/shop/shop-item/StoreVars";`

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/admin/login/login.vue
>                  this.token = data.token;
This is not needed, at line 75 you can just say. `store.token = data.token`

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/admin/login/login.vue
>                  this.token = "";
Here you can say that `store.token = ""`

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/admin/login/login.vue
> +                const store = StoreVars();
I would do this before the try.

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/shared/order/cart-items/cart-items.vue
> +        this.$parent.$data.totalPrice = this.$parent.$data.totalPrice - storageProduct.price;
You can write this as follows:
`this.$parent.$data.totalPrice -= storageProduct.price;`

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/shared/order/shopping-cart.vue
> +        this.totalPrice = this.totalPrice + product.price;
You can change this as follows:
`this.totalPrice += product.price;`

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/shared/order/shopping-cart.vue
> +      const store = StoreVars();
Would it be possible to use it as a variable in data(). Try to deep yourself into it.

2023-06-05 11:06 UTC, DragonTamer117 commented on src/components/shop/shop-content.vue
> +  // eslint-disable-next-line vue/no-unused-components
This is not allowed.

2023-06-05 11:06 UTC, DragonTamer117 commented on src/main.js
> +import {createPinia} from "pinia";
Change it accordingly to: `import { createPinia } from "pinia";`

2023-06-05 11:06 UTC, DragonTamer117 commented on src/router.js
> +        { name: 'shopping-cart-component', path: '/order', meta: { needsAuth: true }, components: { default: Order } },
What is the authentication you are using?

2023-06-05 11:42 UTC, DragonTamer117 requested changes
There a lot of changes that are needed to be done.

2023-06-05 12:05 UTC, DragonTamer117 commented on src/components/shared/order/shopping-cart.vue
> +      const store = StoreVars();
In voice chat we have handled why it's not possible for now.

2023-06-05 12:06 UTC, DragonTamer117 approved these changes
Looks good, except for some weird <p>'s.

2023-06-05 12:07 UTC, merged